### ISSUE TITLE
Does not work on macOS: Failed opening file

### ISSUE THREAD

**Issue by timstrasser** [CodeAssemblingChicken/honeycombs#2] opened 2022-09-08 19:20 UTC
Error message:
```
Sorry, an error occurred. Please report it to the developer:
panicked at 'Failed opening file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/resources.rs:185:48
```

**Comment by CodeAssemblingChicken** [comment] 2022-09-08 21:08
Thanks for reporting this, the same seems to happen on Windows currently.
Sorry for the inconvenience

**Comment by CodeAssemblingChicken** [comment] 2022-09-08 21:36
The issue is now fixed for windows, could you verify on macOS?

**Closed as not planned** 2024-01-24 16:44 UTC
Labels: bug
